/**
*	@author : Aritra Sarkar
*	@date	: 08-04-2017
*	@purpose: Take solution generated by NuSMV to collate true/false constraint satisfiability
*/

import java.io.*;
import java.util.regex.*;

class GenSoln
{
	public static void main(String args[]) throws IOException
	{
		Analyse obj1 = new Analyse();
		obj1.Regexp(args[1], Integer.parseInt(args[0]));
	}
}

class Analyse
{
	public void Regexp(String pathRepo, int pno) throws IOException
	{
		BufferedReader br;
		BufferedWriter bw;
		
		BufferedReader term = new BufferedReader(new InputStreamReader(System.in));
		
		br = new BufferedReader(new FileReader(pathRepo+"gensoln/opt_nusmv/p"+pno+".txt"));
		bw = new BufferedWriter(new FileWriter(pathRepo+"gensoln/opt_nusmv/p"+pno+"_soln.csv"));
		
		String regex1 = "^(-- specification )(?:.*)(is )(.*)";
		Pattern p1 = Pattern.compile(regex1);
		
		int cno = 0;
		String line;
		while((line = br.readLine()) != null)
		{
			Matcher m1 = p1.matcher(line);
			while(m1.find())
			{	
				bw.write(pno+", "+(cno++)+", "+m1.group(3)+"\n");
			}
		}	
		
		bw.flush();
		bw.close();
		
		br.close();
	}
}
